# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hampel_filter_matrix_cpp <- function(X, k, t0 = 3.0, impute_na = FALSE) {
    .Call(`_vrtility_hampel_filter_matrix_cpp`, X, k, t0, impute_na)
}

matrix_to_rowlist_cpp <- function(mat) {
    .Call(`_vrtility_matrix_to_rowlist_cpp`, mat)
}

extract_band_matrices_cpp <- function(x, row_indices, col_indices, n_cells, n_timepoints, n_bands) {
    .Call(`_vrtility_extract_band_matrices_cpp`, x, row_indices, col_indices, n_cells, n_timepoints, n_bands)
}

restructure_cells_cpp <- function(cell_vals) {
    .Call(`_vrtility_restructure_cells_cpp`, cell_vals)
}

register_vrtility_pixel_functions <- function() {
    .Call(`_vrtility_register_vrtility_pixel_functions`)
}

